@startuml menu_state_machine
'MIT License
'
'Copyright (c) 2023 Picorims alias Charly Schmidt
'
'Permission is hereby granted, free of charge, to any person obtaining a copy
'of this software and associated documentation files (the "Software"), to deal
'in the Software without restriction, including without limitation the rights
'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
'copies of the Software, and to permit persons to whom the Software is
'furnished to do so, subject to the following conditions:
'
'The above copyright notice and this permission notice shall be included in all
'copies or substantial portions of the Software.
'
'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
'SOFTWARE.

!theme cyborg-outline
skinparam BackgroundColor #222222

state ShowUserInfo
state ShowGameInfo
state AddPlayer

[*] --> MainMenu: init

MainMenu --> Login: login
MainMenu --> [*]: quit

Login --> LoggedInMenu: logged in [user type]
Login --> MainMenu: back

state LoggedInMenu #113355 {
    state logout <<exitPoint>>

    state loginChoice <<choice>>
    [*] --> loginChoice
    loginChoice --> UserMenu: [user type = user]
    loginChoice --> AdminMenu: [user type = admin]

    state AdminMenu #113355
    AdminMenu --> logout: logout
    AdminMenu --> CreateBot: create bot
    AdminMenu --> [*]

    CreateBot --> AdminMenu: back

    state UserMenu #113355 {
        state userChoice <<choice>>
        userChoice --> ChildMenu: [user type = child]
        userChoice --> AdultMenu: [user type = adult]

        state ChildMenu #113355

        state AdultMenu #113355
        AdultMenu --> AddTutor: add tutor

        AddTutor --> AdultMenu: back
    }
    UserMenu --> AddFriend: invite
    UserMenu --> RemoveFriend: invite
    UserMenu -up-> GetGame: get game
    UserMenu --> logout: logout
    UserMenu --> ConfirmationScreen: delete account
    UserMenu --> [*]

    ConfirmationScreen --> logout: confirm

    GetGame --> UserMenu: back

    AddFriend --> UserMenu: back

    RemoveFriend --> UserMenu: back
}
logout --> MainMenu: logout
LoggedInMenu --> ShowUserInfo: show user info
LoggedInMenu --> ShowGameInfo: show game info
LoggedInMenu --> AddPlayer: add player [not a child]
LoggedInMenu --> Play: play

note right of LoggedInMenu
    An exit point must be taken to leave this state.
end note

ShowUserInfo: <b>Entry</b> [user type = admin or adult] / show all
ShowUserInfo: <b>Entry</b> [user type = child] / show restricted
ShowUserInfo --> LoggedInMenu: back

ShowGameInfo --> LoggedInMenu: back

AddPlayer --> LoggedInMenu: back

Play --> ChooseFriend: play with friend
Play --> Playing: play with bot

ChooseFriend --> Playing: play
ChooseFriend --> Play: back

Playing --> LoggedInMenu: played

@enduml